# Dockerfile-etl
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY etl/ ./etl/
COPY config.py .

CMD ["python", "-m", "etl.etl_runner", "2025-04-05"]
