# Dockerfile-api
FROM python:3.9-slim

WORKDIR /app

# Copiar requirements.txt e instalar dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar arquivos da API e do arquivo de configurações
COPY api/ ./api/
COPY config.py .

# Definir comando para iniciar o Uvicorn (FastAPI)
ENV UVICORN_CMD "uvicorn api.main:app --host 0.0.0.0 --port 8000"

CMD ["sh", "-c", "$UVICORN_CMD"]
