# Dockerfile-api
FROM python:3.9-slim

WORKDIR /app

# Copia e instala as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia os arquivos da API e o arquivo de configurações
COPY api/ ./api/
COPY config.py .

# Define o comando para iniciar a API com Uvicorn
ENV UVICORN_CMD="uvicorn api.main:app --host 0.0.0.0 --port 8000"
CMD ["sh", "-c", "$UVICORN_CMD"]
